# Init

In [1]:
import os
os.environ["CUDA_DEVICE_ORDER"]="PCI_BUS_ID"   # see issue #152
os.environ["CUDA_VISIBLE_DEVICES"]="0"



In [2]:
from peft import (
    get_peft_model,
    LoraConfig,
    TaskType,
    prepare_model_for_int8_training,
)
from peft import PeftModel

In [3]:
import os
import argparse

parser = argparse.ArgumentParser()

# Adding optional argument
parser.add_argument("-c", "--CombinationIdx", type=int, help="Set idx of c to use")
parser.add_argument("-q", "--quantization", action="store_true")
parser.add_argument("--lora_r", type=int, default=8, help="Set LoRA r value")
parser.add_argument(
    "--model_size", type=int, default=7, help="Llama 2 size: 7, 13, or 70"
)
parser.add_argument(
    "--toPredict", default="Target", help="Target vs Source"
)
parser.add_argument(
    "--gpu",
    type=str,
    default="0",
    help="On which GPU to run",
)
parser.add_argument(
    "--nTest",
    type=int,
    default=200,
    help="Number of testing samples",
)
args = parser.parse_args(args=["--model_size=7", "-c=1355", '--lora_r=8', "--toPredict=Target", "--gpu=2", "--nTest=500","--quantization"])

In [4]:
args

Namespace(CombinationIdx=1355, quantization=True, lora_r=8, model_size=7, toPredict='Target', gpu='2', nTest=500)

In [5]:

import sys
import itertools
from tqdm.auto import tqdm
import pathlib
import numpy as np
import pandas as pd
from sklearn.metrics import average_precision_score

import datasets
from contextlib import nullcontext
import torch
from torch import nn
from transformers import (
    Trainer,
    TrainingArguments,
    LlamaTokenizer,
    LlamaForSequenceClassification,
    TrainerCallback,
    default_data_collator,
)


In [6]:
class train_config:
    def __init__(self):
        self.quantization: bool = False

        


globalconfig = train_config()
globalconfig.quantization = args.quantization
globalconfig.model_id = f"/bime-munin/llama2_hf/llama-2-{args.model_size}b_hf/"

# Load Model

In [7]:
target_model_id = "/bime-munin/xiruod/llama2_SHAC/n500/set-1355-quantization-epoch3-llama-2-7B-loraR-8"
source_model_id = "/bime-munin/xiruod/llama2_SHAC/n500/Source-set-1355-quantization-epoch3-llama-2-7B-loraR-8"



In [8]:
##### Tokenizer
tokenizer = LlamaTokenizer.from_pretrained(f"/bime-munin/llama2_hf/llama-2-7b_hf/")

tokenizer.add_special_tokens({"pad_token": "<pad>"})

1

In [9]:
model = LlamaForSequenceClassification.from_pretrained(globalconfig.model_id, device_map='auto', load_in_8bit=args.quantization, torch_dtype=torch.float16)

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

Some weights of LlamaForSequenceClassification were not initialized from the model checkpoint at /bime-munin/llama2_hf/llama-2-7b_hf/ and are newly initialized: ['score.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [10]:
model.config.pad_token_id = tokenizer.pad_token_id

model.resize_token_embeddings(len(tokenizer), pad_to_multiple_of=128)


Embedding(32128, 4096)

# Load Adapter and Manipulation

In [11]:
model = PeftModel.from_pretrained(model, target_model_id, adapter_name='target')

In [12]:

model.load_adapter(source_model_id, adapter_name="source")

_IncompatibleKeys(missing_keys=['base_model.model.model.embed_tokens.weight', 'base_model.model.model.layers.0.self_attn.q_proj.base_layer.weight', 'base_model.model.model.layers.0.self_attn.q_proj.lora_A.target.weight', 'base_model.model.model.layers.0.self_attn.q_proj.lora_B.target.weight', 'base_model.model.model.layers.0.self_attn.k_proj.weight', 'base_model.model.model.layers.0.self_attn.v_proj.base_layer.weight', 'base_model.model.model.layers.0.self_attn.v_proj.lora_A.target.weight', 'base_model.model.model.layers.0.self_attn.v_proj.lora_B.target.weight', 'base_model.model.model.layers.0.self_attn.o_proj.weight', 'base_model.model.model.layers.0.mlp.gate_proj.weight', 'base_model.model.model.layers.0.mlp.up_proj.weight', 'base_model.model.model.layers.0.mlp.down_proj.weight', 'base_model.model.model.layers.0.input_layernorm.weight', 'base_model.model.model.layers.0.post_attention_layernorm.weight', 'base_model.model.model.layers.1.self_attn.q_proj.base_layer.weight', 'base_model

## Play with Adapter Manipulation

In [13]:
import math

In [14]:
import peft

In [15]:
from peft.utils import (
    # TRANSFORMERS_MODELS_TO_LORA_TARGET_MODULES_MAPPING,
    # ModulesToSaveWrapper,
    _freeze_adapter,
    _get_submodules,
    # get_quantization_config,
)

In [16]:
from peft.tuners.lora import LoraLayer

In [17]:
from dataclasses import asdict, replace
from functools import reduce
import operator

In [18]:
adapter_name = 'delta'
adapters = ['target', 'source']

adapters_ranks = [model.peft_config[adapter].r for adapter in adapters]
new_rank = adapters_ranks[0]

target_module_types = [type(model.peft_config[adapter].target_modules) for adapter in adapters]
if target_module_types[0] == str:
    new_target_modules = "|".join(f"({model.peft_config[adapter].target_modules})" for adapter in adapters)
elif target_module_types[0] == set:
    new_target_modules = reduce(
        operator.or_, (model.peft_config[adapter].target_modules for adapter in adapters)
    )

In [19]:
new_target_modules

{'q_proj', 'v_proj'}

In [20]:
model.peft_config[adapter_name] = replace(
            model.peft_config[adapters[0]],
            r=new_rank,
            lora_alpha=new_rank,
            target_modules=new_target_modules,
        )
model.inject_adapter(model.model, adapter_name)

# Do we really need that?
_freeze_adapter(model.model, adapter_name)

In [21]:
key_list = [key for key, _ in model.model.named_modules() if model.prefix not in key]
for key in key_list:
    _, target, _ = _get_submodules(model.model, key)
    if isinstance(target, LoraLayer):
        if adapter_name in target.lora_A:
            target_lora_A = target.lora_A[adapter_name].weight
            target_lora_B = target.lora_B[adapter_name].weight
        elif adapter_name in target.lora_embedding_A:
            target_lora_A = target.lora_embedding_A[adapter_name]
            target_lora_B = target.lora_embedding_B[adapter_name]
        else:
            continue
            
        target_lora_A.data = target_lora_A.data * 0.0
        target_lora_B.data = target_lora_B.data * 0.0
        
        target_lora_A.data = target.lora_A['target'].weight - target.lora_A['source'].weight
        target_lora_B.data = target.lora_B['target'].weight - target.lora_B['source'].weight

## Verify some results

In [22]:
i = 2
model.base_model.model.model.layers[i].self_attn.q_proj.lora_A.target.weight

Parameter containing:
tensor([[ 0.0109,  0.0153, -0.0055,  ..., -0.0022,  0.0044,  0.0006],
        [-0.0076, -0.0081,  0.0033,  ..., -0.0114, -0.0124, -0.0053],
        [-0.0155, -0.0072,  0.0006,  ..., -0.0087,  0.0047,  0.0035],
        ...,
        [ 0.0162,  0.0151,  0.0047,  ...,  0.0080, -0.0051, -0.0144],
        [ 0.0111,  0.0134,  0.0002,  ...,  0.0062, -0.0006,  0.0092],
        [ 0.0123,  0.0111, -0.0155,  ..., -0.0023, -0.0092,  0.0164]],
       device='cuda:0', requires_grad=True)

In [23]:
model.base_model.model.model.layers[i].self_attn.q_proj.lora_A.source.weight

Parameter containing:
tensor([[-0.0005,  0.0104, -0.0027,  ..., -0.0083,  0.0067, -0.0059],
        [ 0.0049, -0.0022, -0.0096,  ...,  0.0040,  0.0041, -0.0020],
        [ 0.0136, -0.0037, -0.0033,  ...,  0.0034, -0.0149, -0.0146],
        ...,
        [-0.0039,  0.0060,  0.0051,  ...,  0.0044,  0.0038,  0.0051],
        [-0.0042,  0.0079, -0.0011,  ..., -0.0014,  0.0029, -0.0080],
        [ 0.0127, -0.0015,  0.0055,  ...,  0.0044, -0.0059,  0.0054]],
       device='cuda:0')

In [24]:
model.base_model.model.model.layers[i].self_attn.q_proj.lora_A.delta.weight

Parameter containing:
tensor([[ 0.0114,  0.0048, -0.0028,  ...,  0.0062, -0.0022,  0.0066],
        [-0.0126, -0.0059,  0.0128,  ..., -0.0155, -0.0165, -0.0034],
        [-0.0291, -0.0035,  0.0040,  ..., -0.0121,  0.0196,  0.0182],
        ...,
        [ 0.0201,  0.0091, -0.0004,  ...,  0.0036, -0.0089, -0.0194],
        [ 0.0154,  0.0055,  0.0013,  ...,  0.0076, -0.0035,  0.0172],
        [-0.0004,  0.0126, -0.0210,  ..., -0.0067, -0.0033,  0.0109]],
       device='cuda:0')

## Save Edited Adapter

In [ ]:
# use adapter "delta"
model.set_adapter("delta")


In [106]:
model.modules_to_save

{'classifier', 'score'}

In [26]:
model.delete_adapter("target")

In [27]:
model.delete_adapter("source")

In [28]:
model.save_pretrained(f"../output/tmpData/{os.path.basename(target_model_id)}/")

/home/NETID/xiruod/anaconda3/envs/llama2/lib/python3.9/site-packages/peft/utils/save_and_load.py:154: UserWarning: Could not find a config file in /bime-munin/llama2_hf/llama-2-7b_hf/ - will assume that the vocabulary was not modified.
  warnings.warn(


# Load Edited Adapter

In [12]:
model = PeftModel.from_pretrained(model, "../output/tmpData/set-1355-quantization-epoch3-llama-2-7B-loraR-8/delta/", adapter_name='delta')

In [13]:
model

PeftModelForSequenceClassification(
  (base_model): LoraModel(
    (model): LlamaForSequenceClassification(
      (model): LlamaModel(
        (embed_tokens): Embedding(32128, 4096)
        (layers): ModuleList(
          (0-31): 32 x LlamaDecoderLayer(
            (self_attn): LlamaAttention(
              (q_proj): lora.Linear8bitLt(
                (base_layer): Linear8bitLt(in_features=4096, out_features=4096, bias=False)
                (lora_dropout): ModuleDict(
                  (delta): Dropout(p=0.05, inplace=False)
                )
                (lora_A): ModuleDict(
                  (delta): Linear(in_features=4096, out_features=8, bias=False)
                )
                (lora_B): ModuleDict(
                  (delta): Linear(in_features=8, out_features=4096, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
              )
              (k_proj): Linear8bitLt(in_features=4096, out

In [14]:
model.eval()

PeftModelForSequenceClassification(
  (base_model): LoraModel(
    (model): LlamaForSequenceClassification(
      (model): LlamaModel(
        (embed_tokens): Embedding(32128, 4096)
        (layers): ModuleList(
          (0-31): 32 x LlamaDecoderLayer(
            (self_attn): LlamaAttention(
              (q_proj): lora.Linear8bitLt(
                (base_layer): Linear8bitLt(in_features=4096, out_features=4096, bias=False)
                (lora_dropout): ModuleDict(
                  (delta): Dropout(p=0.05, inplace=False)
                )
                (lora_A): ModuleDict(
                  (delta): Linear(in_features=4096, out_features=8, bias=False)
                )
                (lora_B): ModuleDict(
                  (delta): Linear(in_features=8, out_features=4096, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
              )
              (k_proj): Linear8bitLt(in_features=4096, out

# add_weighted_adapter: Failed with negative weights...?

In [52]:
model.add_weighted_adapter(["target", "source"], [9, 4], combination_type="linear", adapter_name="diff")

In [62]:
model.delete_adapter('diff')

In [57]:
model.base_model.model.model.layers[2].self_attn.q_proj.scaling

{'target': 4.0, 'source': 4.0, 'diff': 1.0}

In [58]:
i = 2
model.base_model.model.model.layers[i].self_attn.q_proj.lora_A.target.weight

Parameter containing:
tensor([[ 0.0109,  0.0153, -0.0055,  ..., -0.0022,  0.0044,  0.0006],
        [-0.0076, -0.0081,  0.0033,  ..., -0.0114, -0.0124, -0.0053],
        [-0.0155, -0.0072,  0.0006,  ..., -0.0087,  0.0047,  0.0035],
        ...,
        [ 0.0162,  0.0151,  0.0047,  ...,  0.0080, -0.0051, -0.0144],
        [ 0.0111,  0.0134,  0.0002,  ...,  0.0062, -0.0006,  0.0092],
        [ 0.0123,  0.0111, -0.0155,  ..., -0.0023, -0.0092,  0.0164]],
       device='cuda:0', requires_grad=True)

In [59]:
model.base_model.model.model.layers[i].self_attn.q_proj.lora_A.source.weight

Parameter containing:
tensor([[-0.0005,  0.0104, -0.0027,  ..., -0.0083,  0.0067, -0.0059],
        [ 0.0049, -0.0022, -0.0096,  ...,  0.0040,  0.0041, -0.0020],
        [ 0.0136, -0.0037, -0.0033,  ...,  0.0034, -0.0149, -0.0146],
        ...,
        [-0.0039,  0.0060,  0.0051,  ...,  0.0044,  0.0038,  0.0051],
        [-0.0042,  0.0079, -0.0011,  ..., -0.0014,  0.0029, -0.0080],
        [ 0.0127, -0.0015,  0.0055,  ...,  0.0044, -0.0059,  0.0054]],
       device='cuda:0')

In [60]:
model.base_model.model.model.layers[i].self_attn.q_proj.lora_A.diff.weight

Parameter containing:
tensor([[ 0.0627,  0.1544, -0.0492,  ..., -0.0629,  0.0667, -0.0318],
        [-0.0161, -0.0621, -0.0378,  ..., -0.0443, -0.0496, -0.0439],
        [-0.0115, -0.0654, -0.0161,  ..., -0.0318, -0.0609, -0.0667],
        ...,
        [ 0.0736,  0.1268,  0.0589,  ...,  0.0747, -0.0075, -0.0558],
        [ 0.0412,  0.1281, -0.0052,  ...,  0.0285,  0.0140,  0.0073],
        [ 0.1501,  0.0572, -0.0595,  ...,  0.0129, -0.0902,  0.1306]],
       device='cuda:0')

In [61]:
0.0109 * 6 + (-0.0005 * math.sqrt(4*9))

0.0624

# Predict

In [15]:
sys.path.append("../src")

from utils import number_split, create_mix


from data_process import load_wls_adress_AddDomain
from process_SHAC import load_process_SHAC



class train_config:
    def __init__(self):
        self.quantization: bool = False

        


globalconfig = train_config()
globalconfig.quantization = args.quantization
globalconfig.model_id = f"/bime-munin/llama2_hf/llama-2-{args.model_size}b_hf/"
globalconfig.max_seq_length = 1024
globalconfig.num_train_epochs = 3
globalconfig.runs = 1
globalconfig.lr = 1e-4
globalconfig.warmup_ratio = 0.1
globalconfig.lora_r = args.lora_r
globalconfig.profiler = False
globalconfig.device = "cuda:0"

if args.model_size == 70:
    # os.environ["CUDA_VISIBLE_DEVICES"] = "0,1"
    globalconfig.per_device_train_batch_size = 1 #2
    globalconfig.per_device_eval_batch_size = 1 #2
    

else:
    # os.environ["CUDA_VISIBLE_DEVICES"] = "0"
    globalconfig.per_device_train_batch_size = 8
    globalconfig.per_device_eval_batch_size = 8
    

if args.quantization:
    dir_q_snippet = "quantization"
else:
    dir_q_snippet = "NOquantization"

# globalconfig.output_dir = f"~/llama2_SHAC/n200/set-{args.CombinationIdx}-{dir_q_snippet}-epoch3-llama-2-{args.model_size}B-loraR-{args.lora_r}"


######  Load Data

### SHAC

z_category = ["uw", "mimic"]
y_cat = ["False", "True"]

txt_col = "text"
domain_col = "location"

if args.toPredict == "Target":
    label = "Drug"
    globalconfig.output_dir = f"/bime-munin/xiruod/llama2_SHAC/n{args.nTest}/set-{args.CombinationIdx}-{dir_q_snippet}-epoch3-llama-2-{args.model_size}B-loraR-{args.lora_r}"

    label2id = {z: idx for idx, z in zip(range(len(y_cat)), y_cat)}
    id2label = {idx: z for idx, z in zip(range(len(y_cat)), y_cat)}

    df_shac = load_process_SHAC(replaceNA="all")

    df_shac["label_binary"] = df_shac.apply(lambda x: 1 if x[label] else 0, axis=1)
    df_shac["dfSource"] = df_shac[domain_col]
    
elif args.toPredict == "Source":
    label = "location"
    globalconfig.output_dir = f"/bime-munin/xiruod/llama2_SHAC/n{args.nTest}/Source-set-{args.CombinationIdx}-{dir_q_snippet}-epoch3-llama-2-{args.model_size}B-loraR-{args.lora_r}"

    label2id = {z: idx for idx, z in zip(range(len(z_category)), z_category)}
    id2label = {idx: z for idx, z in zip(range(len(z_category)), z_category)}

    df_shac = load_process_SHAC(replaceNA="all")

    df_shac["label_binary"] = df_shac.apply(lambda x: label2id[x[label]], axis=1)
    df_shac["dfSource"] = df_shac[domain_col]
    
else:
    sys.exit("Unknown Outcome: 'Target' and 'Source' ONLY")

df_shac_uw = df_shac.query("location == 'uw'").reset_index(drop=True)
df_shac_mimic = df_shac.query("location == 'mimic'").reset_index(drop=True)

##### Split
# SHAC-Drug - Balanced Alpha
n_test = args.nTest
train_test_ratio = 4


p_pos_train_z0_ls = np.arange(
    0, 1, 0.1
)  # probability of training set examples drawn from site/domain z0 being positive
p_pos_train_z1_ls = np.arange(
    0, 1, 0.1
)  # probability of test set examples drawn from site/domain z1 being positive

p_mix_z1_ls = np.arange(0, 1, 0.05)

numvals = 1023
base = 1.1
alpha_test_ls = np.power(base, np.arange(numvals)) / np.power(base, numvals // 2)

valid_full_settings = []
for combination in itertools.product(
    p_pos_train_z0_ls, p_pos_train_z1_ls, p_mix_z1_ls, alpha_test_ls
):
    number_setting = number_split(
        p_pos_train_z0=combination[0],
        p_pos_train_z1=combination[1],
        p_mix_z1=combination[2],
        alpha_test=combination[3],
        train_test_ratio=train_test_ratio,
        n_test=n_test,
        verbose=False,
    )

    if number_setting is not None:
        if np.all([number_setting[k] >= 10 for k in list(number_setting.keys())[:-1]]):
            valid_full_settings.append(number_setting)


# run for check valid settings

import warnings

warnings.simplefilter("ignore")

# Validate settings

df0 = df_shac_uw
df1 = df_shac_mimic

/home/NETID/xiruod/projects/DeconDTN/notebooks_xiruo/../src/utils.py:29: RuntimeWarning: invalid value encountered in scalar divide
  alpha_train = p_pos_train_z1 / p_pos_train_z0
/home/NETID/xiruod/projects/DeconDTN/notebooks_xiruo/../src/utils.py:29: RuntimeWarning: divide by zero encountered in scalar divide
  alpha_train = p_pos_train_z1 / p_pos_train_z0


In [17]:
valid_n_full_settings = []

for c in tqdm(valid_full_settings):
    c = c.copy()
    # create train/test split according to stats
    dfs = create_mix(df0=df0, df1=df1, target=label if args.toPredict == "Target" else "Drug", setting=c, sample=False, seed=222)

    if dfs is None:
        continue

    valid_n_full_settings.append(c)
    break

  0%|          | 0/46811 [00:00<?, ?it/s]

In [18]:
##### Dataset Loader and Tokenizer
def preprocess_function(examples):
    # tokenize
    ret = tokenizer(
        examples[txt_col],
        return_tensors="pt",
        max_length=globalconfig.max_seq_length,
        padding="max_length",
        truncation=True,
    ).to(globalconfig.device)

    return ret


def datasets_loader(df):
    # from pandas df to Dataset & tokenize
    ret_datasets = datasets.Dataset.from_pandas(
        df[[txt_col, "dfSource", "label_binary"]]
        .rename(columns={"label_binary": "label"})
        .reset_index(drop=True)
    )
    ret_tokenized = ret_datasets.map(preprocess_function, batched=True)

    return ret_tokenized


##### Experiment - ONLY One Setting

print("Balanced? Check setting....")
print(c)
dfs = create_mix(
    df0=df0,
    df1=df1,
    target=label if args.toPredict == "Target" else "Drug",
    setting=c,
    sample=False,
    # seed=random.randint(0,1000),
    seed=222,
)

tokenized_train = datasets_loader(dfs["train"])
tokenized_test = datasets_loader(dfs["test"])


## Define metric
def compute_metrics_twoLevels(eval_pred):
    # compute AUPRC, based on only two levels of Y
    predictions, labels = eval_pred
    probabilities = nn.functional.softmax(torch.FloatTensor(predictions), dim=-1)[:, 1]

    auprc = average_precision_score(y_true=labels, y_score=probabilities)

    return {"auprc": auprc}

Balanced? Check setting....
{'n_train': 2000, 'n_test': 500, 'n_z0_pos_train': 130, 'n_z0_neg_train': 1170, 'n_z0_pos_test': 40, 'n_z0_neg_test': 285, 'n_z1_pos_train': 70, 'n_z1_neg_train': 630, 'n_z1_pos_test': 10, 'n_z1_neg_test': 165, 'mix_param_dict': {'p_pos_train_z0': 0.1, 'p_pos_train_z1': 0.1, 'p_pos_train': 0.09999999999999999, 'p_pos_test': 0.09999999999999999, 'p_mix_z0': 0.6499999999999999, 'p_mix_z1': 0.35000000000000003, 'alpha_train': 1.0, 'alpha_test': 0.4665073802097331, 'p_pos_test_z0': 0.12295924796315696, 'p_pos_test_z1': 0.05736139663985131, 'C_y': 0.09999999999999999, 'C_z': 0.35000000000000003}}


Map:   0%|          | 0/2000 [00:00<?, ? examples/s]

Map:   0%|          | 0/500 [00:00<?, ? examples/s]

In [38]:
df_in = tokenizer(
        list(dfs['test'].iloc[:15]['text']),
        return_tensors="pt",
        max_length=globalconfig.max_seq_length,
        padding="max_length",
        truncation=True,
    )

In [20]:
df_in

{'input_ids': tensor([[    1,   379,  2882,  ..., 32000, 32000, 32000],
        [    1,  7791,  8426,  ..., 32000, 32000, 32000],
        [    1,  7791,  8426,  ..., 32000, 32000, 32000],
        ...,
        [    1, 10307,  5298,  ..., 32000, 32000, 32000],
        [    1, 10307,  5298,  ..., 32000, 32000, 32000],
        [    1,   379,  2882,  ..., 32000, 32000, 32000]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]])}

In [39]:
df_in

{'input_ids': tensor([[    1,   379,  2882,  ..., 32000, 32000, 32000],
        [    1,  7791,  8426,  ..., 32000, 32000, 32000],
        [    1,  7791,  8426,  ..., 32000, 32000, 32000],
        ...,
        [    1,  7791,  8426,  ..., 32000, 32000, 32000],
        [    1,  7791,  8426,  ..., 32000, 32000, 32000],
        [    1, 10307,  5298,  ..., 32000, 32000, 32000]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]])}

In [40]:
df_in['input_ids'].shape

torch.Size([15, 1024])

In [58]:
model.set_adapter('delta')
model.eval()
with torch.no_grad():
    tmp = model(input_ids=df_in['input_ids'], attention_mask=df_in['attention_mask'])

In [59]:
tmp['logits']

tensor([[-0.9814, -1.1426],
        [ 1.8564, -0.2979],
        [ 0.4932, -3.0684],
        [-1.5459, -2.6211],
        [-0.4260, -0.3877],
        [-0.4724, -0.4685],
        [ 1.2012, -1.4082],
        [ 0.0987, -4.5859],
        [-0.5771, -3.2051],
        [-0.9287, -0.7275],
        [ 1.1318, -3.9277],
        [-1.0410, -1.9648],
        [ 1.2861, -2.3691],
        [-0.8003, -2.6777],
        [-0.3035,  0.6147]], dtype=torch.float16)

In [60]:
from scipy.special import softmax

In [61]:
softmax(tmp['logits'], axis=1)

array([[0.54    , 0.4597  ],
       [0.896   , 0.1039  ],
       [0.9727  , 0.02759 ],
       [0.745   , 0.2544  ],
       [0.4902  , 0.5093  ],
       [0.499   , 0.501   ],
       [0.9316  , 0.0686  ],
       [0.991   , 0.00916 ],
       [0.9326  , 0.06726 ],
       [0.4497  , 0.55    ],
       [0.993   , 0.006313],
       [0.7163  , 0.2842  ],
       [0.975   , 0.02519 ],
       [0.867   , 0.1327  ],
       [0.2854  , 0.7144  ]], dtype=float16)

In [37]:
softmax(tmp['logits'], axis=1)[:,1]

array([0.466   , 0.1357  , 0.02461 , 0.2487  , 0.5625  , 0.489   ,
       0.0799  , 0.010826, 0.0621  , 0.4868  , 0.009125, 0.2264  ,
       0.02446 , 0.11005 , 0.7476  , 0.03406 , 0.03656 ], dtype=float16)

In [118]:
len(df_in['input_ids'])

15

In [64]:
l = list(range(len(df_in['input_ids'])))
n = 3
idx_ls = [l[i:i+n] for i in range(len(l)) if i%n==0]

In [65]:
idx_ls

[[0, 1, 2], [3, 4, 5], [6, 7, 8], [9, 10, 11], [12, 13, 14]]

In [66]:
y_ls = []
model.set_adapter('delta')
with torch.no_grad():
    for idx in idx_ls:
        model.eval()

        ret_output = model.forward(input_ids=df_in['input_ids'][idx], attention_mask=df_in['attention_mask'][idx])
        y_probs_ = softmax(ret_output["logits"], axis=1)
        y_ls.append(y_probs_)

In [63]:
np.concatenate(y_ls)

array([[0.498   , 0.502   ],
       [0.8965  , 0.1036  ],
       [0.9727  , 0.02731 ],
       [0.7334  , 0.2664  ],
       [0.5273  , 0.4727  ],
       [0.4792  , 0.521   ],
       [0.934   , 0.06586 ],
       [0.99    , 0.009224],
       [0.942   , 0.0577  ],
       [0.526   , 0.474   ],
       [0.992   , 0.008194],
       [0.7466  , 0.254   ],
       [0.975   , 0.02441 ],
       [0.8604  , 0.139   ],
       [0.2803  , 0.7197  ]], dtype=float16)

In [67]:
np.concatenate(y_ls)

array([[0.549   , 0.4514  ],
       [0.8843  , 0.1153  ],
       [0.977   , 0.02246 ],
       [0.711   , 0.2888  ],
       [0.4614  , 0.5386  ],
       [0.518   , 0.4814  ],
       [0.9233  , 0.07684 ],
       [0.9893  , 0.01095 ],
       [0.934   , 0.06586 ],
       [0.4082  , 0.592   ],
       [0.993   , 0.006588],
       [0.753   , 0.2468  ],
       [0.975   , 0.0247  ],
       [0.872   , 0.1277  ],
       [0.2664  , 0.7334  ]], dtype=float16)

In [13]:
nm = "/bime-munin/xiruod/llama2_SHAC/n500/Targetset-1355-quantization-epoch3-llama-2-7B-loraR-8/"

In [14]:
tmp = [x for x in nm.split("/") if "set-" in x]
name_pre = tmp[0] # of form like set-1355-quantization-epoch3-llama-2-7B-loraR-8
model_size = int(name_pre.split("-")[-3].replace("B", ""))  # 7, 13, 70

In [15]:
tmp

['Targetset-1355-quantization-epoch3-llama-2-7B-loraR-8']

In [11]:
name_pre

'set-1355-quantization-epoch3-llama-2-7B-loraR-8'

In [12]:
model_size

7